# Generated by Django 5.2.4 on 2025-09-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_alter_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='upi_id',
        ),
        migrations.AddField(
            model_name='merchant',
            name='business_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='business_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='password',
            field=models.CharField(default='Password@123', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='api_key',
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
