# Generated by Django 5.2.4 on 2025-09-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0003_remove_merchant_upi_id_merchant_business_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='api_key',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
