# Generated by Django 5.2.4 on 2025-09-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0004_alter_merchant_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='vpa',
            field=models.CharField(default='sample@ybl', max_length=100),
            preserve_default=False,
        ),
    ]
