# Generated by Django 5.2.4 on 2025-09-22 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0005_payment_vpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='gateway.merchant'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('merchant', 'order_id'), name='uniq_merchant_order'),
        ),
    ]
