# Generated by Django 5.2.4 on 2025-09-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0006_alter_payment_merchant_payment_uniq_merchant_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='webhook_secret',
            field=models.CharField(default='fsdzveF', editable=False, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_txn_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
