# Generated by Django 5.2.4 on 2025-10-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0008_remove_payment_timestamp_payment_payer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchant',
            name='otp_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='api_key',
            field=models.CharField(blank=True, editable=False, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='webhook_secret',
            field=models.CharField(blank=True, editable=False, max_length=256, null=True),
        ),
    ]
