# Generated by Django 5.2.4 on 2025-10-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0009_merchant_is_active_merchant_otp_requested_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='callback_url',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='gstin',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='otp_requested_at',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='webhook_secret',
        ),
        migrations.AddField(
            model_name='merchant',
            name='contact_name',
            field=models.CharField(default='sample', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchant',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('proprietorship', 'Proprietorship'), ('partnership_llp', 'Partnership/LLP'), ('pvt_public', 'Pvt. Ltd. / Public Ltd'), ('person_company', 'Person Company'), ('partnership_firm', 'Partnership Firm')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='business_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
