# Generated by Django 5.2.4 on 2025-10-27 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0011_otp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='password',
        ),
        migrations.AddField(
            model_name='merchant',
            name='user',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
