# Generated by Django 5.2.4 on 2025-10-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0012_remove_merchant_email_remove_merchant_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='provider_transaction_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='provider_verification_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
