# Generated by Django 5.2.4 on 2025-10-29 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0013_otp_provider_transaction_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.CharField(max_length=64, unique=True)),
                ('hashed_secret', models.CharField(max_length=128)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('mode', models.CharField(choices=[('test', 'Test'), ('live', 'Live')], default='test', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked', models.BooleanField(default=False)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='gateway.merchant')),
            ],
            options={
                'indexes': [models.Index(fields=['merchant', 'created_at'], name='gateway_api_merchan_093cff_idx'), models.Index(fields=['key_id'], name='gateway_api_key_id_613b42_idx')],
            },
        ),
    ]
