# Generated by Django 5.2.4 on 2025-10-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0014_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='webhook_secret',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider_txn_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
