# Generated by Django 5.2.4 on 2025-11-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0017_alter_payment_status_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='aadhaar_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/aadhaar/'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='gst_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/gst/'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='pan_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/pan/'),
        ),
    ]
