# Generated by Django 5.2.4 on 2025-11-27 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0018_merchant_gst_file_merchant_pan_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='gst_file',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='pan_file',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='signatory_file',
        ),
    ]
