# Generated by Django 5.2.4 on 2025-11-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0018_merchant_aadhaar_file_merchant_gst_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='aadhaar_file',
        ),
        migrations.AddField(
            model_name='merchant',
            name='signatory_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/signatory/'),
        ),
    ]
