# Generated by Django 5.2.4 on 2025-11-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0019_remove_merchant_gst_file_remove_merchant_pan_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='gst_file',
            field=models.FileField(blank=True, null=True, upload_to='merchant_docs/gst/'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='pan_file',
            field=models.FileField(blank=True, null=True, upload_to='merchant_docs/pan/'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='signatory_file',
            field=models.FileField(blank=True, null=True, upload_to='merchant_docs/signatory/'),
        ),
    ]
