# Generated by Django 5.2.4 on 2025-12-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0020_merchant_gst_file_merchant_pan_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login'), ('phone_verify', 'Phone Verification'), ('password_reset', 'Password Reset')], default='login', max_length=32),
        ),
    ]
