# Generated by Django 6.0.1 on 2026-02-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0021_otp_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='provider_status_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
