# Generated by Django 5.2.4 on 2026-03-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0023_alter_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='phonepe_mid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='website_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
